// src/constants/strings.js
export const Strings = {
  splashTitle: 'Checking Connection & Permissions...',
  noInternet: 'No Internet Connection',
  homeWelcome: 'Welcome to Your App!',
  offlineBanner: 'You are currently offline',
  errorTitle: 'An unexpected error occurred',
  datingTab: 'Dating',
  communityTab: 'Community',
  lifePartnerTab: 'Life Partner',
  // On the Login screen, you’re asking the user to enter their phone and request an OTP
  loginTitle: 'Enter your phone number to continue',
  // The button sends the OTP
  submit: 'Send OTP',
  verify: 'Verify OTP',

  // Labels
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  location: 'Location',
  age: 'Age',
  female: 'Female',
  male: 'Male',
  registerTitle: 'Register',
  genderQuestion: 'What is your gender?',
  termsPrefix: 'I accept the ',
  termsLink: 'Terms & Conditions',
  continue: 'Continue',
  // Validation messages
  nameShort: 'Name must be at least 3 characters',
  nameRequired: 'Name is required',
  passShort: 'Password must be 3–8 characters',
  passLong: 'Password too long',
  passRequired: 'Password is required',
  invalidEmail: 'Enter a valid email',
  emailRequired: 'Email is required',
  locationShort: 'Location too short',
  locationLong: 'Location too long',
  locationRequired: 'Location is required',
  ageInvalid: 'Enter a valid two‐digit age',
  ageRequired: 'Age is required',
  genderRequired: 'Select a gender',
  termsRequired: 'You must accept terms',
  checkConnection: 'Please check your connection.',
  registrationSuccess: 'Registration successful!',
  registrationFailed: 'Registration failed. Please try again.',
  somethingWrong: 'Something went wrong. Please try later.',
  error: 'Error',

  // **ICON NAMES** for each field
  icons: {
    firstName: 'account',
    lastName: 'account',
    email: 'email',
    location: 'map-marker',
    age: 'calendar',
    female: 'woman-outline',
    male: 'man-outline',
  },
};
